config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :costumes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :offers, only: [:new, :create]
  end
  resources :offers, only: [:index, :show, :destroy] do
    member do
      post "accept"
      post "cancel"
    end
  end
  get "/test", to: "pages#test"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costume.rb
class Costume < ApplicationRecord
  belongs_to :user
  has_many :offers, dependent: :destroy
  has_many_attached :photos
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :title, :price, :location, presence: true
  validates :title, length: { minimum: 5, maximum: 60 }
  validates :price, numericality: true

  include PgSearch::Model
  pg_search_scope :search_by_location,
                  against: [:location],
                  using: { tsearch: { prefix: true } }
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :costume
  validates :date_of_hire, :duration, presence: true
  validates :duration, numericality: { only_integer: true }
  validates :status, inclusion: ['pending', 'accepted', 'rejected']

  def date_of_end
    date_of_hire + duration
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :costumes, dependent: :destroy
  has_many :offers, dependent: :destroy
  validates :username, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @costumes = policy_scope(Costume)
    @markers = @costumes.geocoded.map do |costume|
      {
        lat: costume.latitude,
        lng: costume.longitude,
        info_window: render_to_string(partial: "info_window", locals: { costume: costume })

      }
    end
  end

  def new
    @costume = Costume.new
    authorize @costume
  end

  def show
    @costume = Costume.find(params[:id])
    @user = current_user
    @offer = Offer.new
    authorize @costume
    @markers = [
      {
        lat: @costume.latitude,
        lng: @costume.longitude,
        info_window: render_to_string(partial: "info_window", locals: { costume: @costume })
      }]
  end

  def create
    @costume = Costume.new(costume_params)
    @user = current_user
    @costume.user_id = current_user.id
    authorize @costume
    if @costume.save
      redirect_to dashboard_path
    else
      redirect_to controller: 'pages', action: 'dashboard', page: 'new'
    end
  end

  def edit
    @costume = Costume.find(params[:id])
    authorize @costume
  end

  def update
    @costume = Costume.find(params[:id])
    @costume.update(costume_params)
    authorize @costume

    redirect_to dashboard_path
  end

  def destroy
    @costume = Costume.find(params[:id])
    @costume.destroy
    authorize @costume

    redirect_to "/dashboard"
  end

  private

  def costume_params
    params.require(:costume).permit(:title, :description, :price, :location, photos: [])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def index
    @offers = policy_scope(Offer).select { |offer| offer.user == current_user }
  end

  def show
    raise
  end

  def new
    @costume = Costume.find(params[:costume_id])
    @offer = Offer.new
    authorize @offer
    authorize @costume
  end

  def create
    @offer = Offer.new(offer_params)
    @costume = Costume.find(params[:costume_id])
    @user = current_user
    @offer.user_id = @user.id
    @offer.costume_id = @costume.id
    @offer.status = "pending"
    authorize @offer
    if @offer.save
      @offer.save
      redirect_to dashboard_path
    else
      render "costumes/show"
    end
  end

  def accept
    @offer = Offer.find(params[:id])
    @offers = Offer.where( costume_id: @offer.costume_id )
    @costume = Costume.find(@offer.costume_id)
    @offers.each do |offer|
      offer.status = "rejected"
      offer.save
    end
    @offer.status = "accepted"
    @offer.save
    authorize @offer

    redirect_to dashboard_path
  end

  def cancel
    @offer = Offer.find(params[:id])
    @offers = Offer.where( costume_id: @offer.costume_id )
    @costume = Costume.find(@offer.costume_id)
    @offers.each do |offer|
      offer.status = "pending"
      offer.save
    end
    authorize @offer

    redirect_to dashboard_path
  end

  def destroy
    @offer = Offer.find(params[:id])
    @costume = Costume.find(@offer.costume_id)
    @offer.destroy
    authorize @offer
    redirect_to dashboard_path
  end

  private

  def offer_params
    params.require(:offer).permit(:date_of_hire, :duration)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :dashboard]

  def home
  end

  def dashboard
    @active_tab = params[:page] || "homepage"
    @my_costumes = Costume.where(user: current_user)
    @costumes = Costume.all
    @costume = Costume.new
    @my_offers = Offer.where(user_id: current_user.id)
    @my_costumes_offers = []
    @my_offers.each do |offer|
      @my_costumes_offers << Costume.find(offer.costume_id)
    end
  end

  def test
    @active_tab = params[:page] || "homepage"
    @my_costumes = Costume.where(user: current_user)
    @costumes = Costume.all
    @costume = Costume.new
    @my_offers = Offer.where(user_id: current_user.id)
    @my_costumes_offers = []
    @my_offers.each do |offer|
    @my_costumes_offers << Costume.find(offer.costume_id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costumes/_card.html.erb
<div class="my-3" style="width: 300px; background-color: white; border-radius: 8px;">
<%= link_to costume_path(costume) do %>
  <div class="card-image-container">
    <img <% if costume.photos.attached? %> >
      <%= cl_image_tag costume.photos.first.key, crop: :pad, class: "grid-image", width: 300, height: 300 %>
    <% else %>
      <%= image_tag costume.image_url, class: "grid-image", crop: :pad %>
    <% end %>
  </div>

<div>
  <div class="_40px-divider"></div>

  <div class="paid-label-container">
    <div class="free-label-text"><%= costume.price %>€</div>
  </div>
  <% if Offer.where( costume_id: costume.id, status: "accepted" ).empty? %>
    <div class="available-label-container">
      <div class="available-label-text">available</div>
    </div>
  <% else %>
    <div class="unavailable-label-container">
      <div class="available-label-text">unavailable</div>
    </div>
  <% end %>

  <div class="_10px-divider"></div>

  <div class="h2-card-title">
    <%= costume.title.upcase %>
  </div>

  <div class="_40px-divider"></div>

  <div class="p-meta">
    <%= costume.description %>
  </div>

  <div class="_40px-divider"></div>
  </div>
  <% end %>

</div>
    <%# </div> %>
  <%# </div> %>
        <%# </div> %>
    <%# </div> %>
<%# </div> %>

app/views/costumes/_card_ring.html.erb
<div class="card-custom-ring" data-controller="modal" data-action="click->modal#openModal">
  <div class="card-image" style="background-image: url(<%= cl_image_path costume.photos.first.key, crop: :fit %>)">
    <h4 class="card-costume-title"><%= costume.title.upcase %></h4>
  </div>
  <%# The '%.2f' ensures that the number returned always has 2 decimal places (important for displaying currency) %>
    <h6 class="costume-price"><%= '%.2f' % costume.price %>€</h6>
    <%= render 'costumes/show_costume', costume: costume %>
</div>

app/views/costumes/_carousel.html.erb
<div class="carousel-wrapper">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-controller="show">
    <div class="carousel-inner">
      <% costume.photos.each do |photo| %>
        <div class="carousel-item" data-show-target="item">
          <%= cl_image_tag photo.key, crop: :fit, class: "d-block carousel-photo" %>
        </div>
      <% end %>
    </div>
    <div class="carousel-control carousel-control-prev" role="button" data-slide="prev" data-action="click->show#previous">
      <i class="fas fa-chevron-circle-left"></i>
    </div>
    <div class="carousel-control carousel-control-next" role="button" data-slide="next" data-action="click->show#next">
      <i class="fas fa-chevron-circle-right"></i>
    </div>
  </div>
</div>

app/views/costumes/_display_costume.html.erb
<div class="costume-info">
  <div class="show-info-body">
    <div class="images-container">
      <div class="images-list">
        <% costume.photos.each do |photo| %>
          <%= cl_image_tag photo.key, crop: :fit, class: "image-list-single" %>
        <% end %>
      </div>
      <%= render 'costumes/carousel', costume: costume %>
    </div>
    <div class="show-info">
      <div>
        <h2 class="show-info-header"><%= costume.title.upcase %></h2>
        <div class="description-wrapper">
          <h5><strong>About this costume</strong></h5>
          <p class="show-info-description"><%= costume.description %></p>
        </div>
      </div>
      <div class="show-info-details">
        <h3><strong>Price per day</strong></h3>
        <p><%= '%.2f' % costume.price %>€</p>
        <h3><strong>Location</strong></h3>
        <p><%= costume.location %></p>
        <h3><strong>Owned by</strong></h3>
        <p><%= costume.user.username.capitalize %></p>
        <h5 class="costume-status">Available</h5>
      </div>
      <%# <% if policy(costume).destroy? %>
        <%# <%= link_to 'Delete', costume_path(costume.id), method: :delete, data: { confirm: "Are you sure?" } %>
      <%# end %>
      <%# <%= link_to "Back", "/dashboard" %>
    </div>
  </div>
</div>

app/views/costumes/_info_window.html.erb
<div class="container">
  <h2><%= costume.title %></h2>
  <%= cl_image_tag costume.photos.first.key, width: 300, height: 350, crop: :fit%>
  <p><%= costume.location %></p>
</div>

app/views/costumes/_map.html.erb
<div style="width: 100%; height: 100%;"
     id="map"
     data-controller="mapbox"
     data-mapbox-markers-value="<%= markers.to_json %>"
     data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
>
</div>

app/views/costumes/_maps.html.erb
<div style="width: 100%; height: 100%;"
     id="map"
     data-controller="mapbox"
     data-mapbox-markers-value="<%= markers.to_json %>"
     data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
>
</div>

app/views/costumes/_new_edit.html.erb
<div class="container">
  <%= simple_form_for costume do |f| %>
    <%= f.input :title %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :location %>
    <div ontouchstart="">
      <div class="button-fast">
        <%= f.submit "Go Faster !", class: "button resize" %>
      </div>
    </div>
  <% end %>
</div>

app/views/costumes/_owner_options.html.erb
<% offers = Offer.where( costume_id: costume.id) %>
<% if offers.empty? %>
  <p>You haven't recieved any offers on this costume.</p>
<% else %>
  <% offers.each do |offer| %>
    <%= render 'offers/offers-card', offer: offer, costume: costume %>
  <% end %>
<% end %>

app/views/costumes/_search-costumes.html.erb
<ul class="display-cards">
  <% costumes.each do |costume| %>
    <li>
      <%# <%= link_to costume_path(costume) do %>
        <%= render '/costumes/card_ring', costume: costume %>
      <%# <% end %>
    </li>
  <% end %>
</ul>

app/views/costumes/_show_costume.html.erb
<div class="modal-wrapper" data-controller="modal" data-modal-target="container" >
  <div class="modal-custom" id="show-page" data-modal-target="modal">
    <div class="modal-close" data-action="click->modal#closeModal"><i class="far fa-times-circle"></i></div>
    <div class="modal-custom-content">
      <%= render 'costumes/display_costume', costume: costume %>
      <div class="costume-options">
        <div class="map-container">
        </div>
          <div class="costume-menu" data-controller="ownerTab">
            <% if policy(costume).edit? %>
                <div class="owner-tabs-wrapper">
                  <p class="owner-tab active" data-ownerTab-target='tab' data-action="click->ownerTab#changeTab" data-tab-page='offers' >Offers received</p>
                  <p class="owner-tab" data-ownerTab-target='tab' data-action="click->ownerTab#changeTab" data-tab-page='edit' >Edit Costume</p>
                </div>
              <div class="options-wrapper">
                <div id="offers" data-ownerTab-target="tabPage">
                  <%= render 'costumes/owner_options', costume: costume %>
                </div>
                <div class="hidden" id="edit" data-ownerTab-target="tabPage">
                  <%= render 'costumes/new_edit', costume: costume %>
                </div>
                </div>
            <% elsif Offer.find { |offer| offer.costume_id == costume.id && offer.user_id == current_user.id } %>
              <% offer = Offer.find { |offer| offer.costume_id == costume.id && offer.user_id == current_user.id } %>
              <h3>You have put an offer on this costume !</h3>
              <%= link_to 'Delete my offer', offer_path(offer.id), method: :delete, data: { confirm: "Are you sure?" } %>
              <br>
            <% elsif Offer.find { |offer| offer.costume_id == costume.id && offer.status == "accepted" } %>
              <p>This costume is not available</p>
            <% else%>
              <div class="content-form">
                <h2>Is it to your tastes?</h2>
                <p>You can rent it</p>
                <% offer = Offer.new %>
                <%= render "/offers/new.html.erb", costume: costume, offer: offer %>
              </div>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/costumes/edit.html.erb
<div class="container">
  <%= simple_form_for @costume do |f| %>
    <%= f.input :title %>
    <%= f.input :price %>
    <%= f.input :description %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :location %>
    <%= f.submit "Go Faster" %>
  <% end %>
  <br>
  <%= link_to "Back", "/costumes" %>
</div>

app/views/costumes/index.html.erb
<div class="index-display" data-controller="indexpage">
  <div class="costumes-container">
    <div class="index-header">
      <h5 class="index-titles mr-6">TOUS LES SONICS PRES DE PARIS</h5>
      <div class="d-flex flex-row-reverse">
        <button class="filter-btn p-2">Availibility</button>
        <button class="filter-btn p-2">By price</button>
        <button class="filter-btn p-2">Filter</button>
      </div>
    </div>
    <%= render 'search-costumes', costumes: @costumes, class:"card-custom" %>
  </div>
  <div class="map-container" data-indexpage-target="mapContainer">
  <div class="map-toggle-button" data-action="click->indexpage#toggle_map_display"><i class="fas fa-angle-right"></i></div>
    <%= render "map" ,markers: @markers %>
  </div>
</div>

app/views/costumes/new.html.erb
<div class="container">
  <%= simple_form_for @costume do |f| %>
    <%= f.input :title %>
    <%= f.input :price %>
    <%= f.input :description %>
   <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :location %>
    <%= f.submit "Go Faster" %>
  <% end %>
  <br>
  <%= link_to "Back", "/costumes" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sonicos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Code+Latin:wght@200;300;400&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/_new.html.erb
  <%= simple_form_for [costume, offer] do |f| %>
    <%= f.date_field :date_of_hire %>
    <%= f.input :duration %>
    <%= f.submit %>
  <% end %>

app/views/offers/_offers-card.html.erb
<div class="container-offers-card">
  <div class="offers-card">
    <div class="avatar">
      <%= image_tag "https://img.huffingtonpost.com/asset/5ff3371b260000ae2b7a3827.jpeg?cache=AfBaoaRwUB&ops=scalefit_630_noupscale", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    </div>
      <div class="offers-card-info">
        <h5><%= offer.user.username %></h5>
        <p>From <%= offer.date_of_hire %> to <%= offer.date_of_end %></p>
      </div>
      <div class="container-price-availibility">
        <div class="paid-label-container">
          <div class="free-label-text"><%= costume.price * offer.duration %>€</div>
        </div>
        <% if offer.status == "accepted" %>
          <div class="available-label-container">
            <div class="available-label-text">
              <%= link_to 'accepted',  cancel_offer_path(offer.id), method: :post, data: { confirm: "Are you sure?" }, style: 'color: white;' %>
            </div>
          </div>
        <% elsif offer.status == "pending" %>
          <div class="pending-label-container">
            <div class="available-label-text">
              <%= link_to 'pending',  accept_offer_path(offer.id), method: :post, data: { confirm: "Are you sure?" }, style: 'color: white;' %>
            </div>
          </div>
        <% else %>
          <div class="unavailable-label-container">
            <div class="available-label-text">rejected</div>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/offers/index.html.erb
<ul>
  <% @offers.each do |offer| %>
    <li>
      <%= render "/costumes/card", costume: offer.costume %>
    </li>
  <% end %>
</ul>

app/views/offers/new.html.erb
<%= form_for [@costume, @offer] do |f| %>
  <%= f.label :date_of_hire %>
  <%= f.date_field :date_of_hire %>
  <%= f.label :duration %>
  <%= f.number_field :duration %>
  <%= f.submit %>
<% end %>

app/views/pages/_homepage.html.erb
<div id="homepage" class="mt-3" data-dashboard-target="section">
  <ul class="display-cards">
    <% if @my_costumes.empty? %>
      <li>You do not currently own any Sonics to see</li>
    <% else %>
      <% @my_costumes.each do |costume| %>
        <li>
          <%# <%= link_to costume_path(costume) do %>
            <%= render '/costumes/card_ring', costume: costume %>
          <%# <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/pages/_new-costume.html.erb
<div id="new" class="mt-3  pb-5 hidden">
<%= simple_form_for costume do |f| %>
  <%= f.input :title %>
  <%= f.input :price %>
  <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :location,
              input_html: { data: { geocoder_target: "location" }, class: "d-none" },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] }, class: "file optional" } %>
<div ontouchstart="">
      <div class="button-fast">
        <%= f.submit "Go Faster !", class: "button" %>
      </div>
    </div>
<% end %>
</div>

app/views/pages/_offers.html.erb
<div id="offers" class="mt-3 hidden" data-dashboard-target="section">
  <h3 class="my-3">My Sonics</h3>
  <ul class="display-cards">
    <% if @my_offers.empty? %>
      <li>You haven't made any offers yet.</li>
    <% else %>
      <% @my_costumes_offers.each do |costume| %>
        <li>
          <%= link_to costume_path(costume) do %>
            <%= render '/costumes/card', costume: costume %>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/pages/_search-costume.html.erb
<div class="hidden mt-3" id="search" data-dashboard-target="section">
  <%= render 'costumes/search-costumes', costumes: @costumes %>
</div>

app/views/pages/_searchbar-button.html.erb
<div class="navbar-button-wrapper">
  <%= button_tag type:"submit", class: "cta" do %>
    <span>Gotta Go Fast !</span>
    <span>
      <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
          <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
          <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
        </g>
      </svg>
    </span>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<div data-controller="dashboard" data-dashboard-target="parent" data-page-to-load=<%= @active_tab %>>
  <div class="dashboard-container">
    <div class="dashboard-tabs">
      <div class="tab active" data-action="click->dashboard#toggle_page" data-dashboard-target="tab" data-page-name="homepage">My Sonics</div>
      <div class="tab" data-action="click->dashboard#toggle_page" data-dashboard-target="tab" data-page-name="search">Sonics near me</div>
      <div class="tab" data-action="click->dashboard#toggle_page" data-dashboard-target="tab" data-page-name="offers">My offers</div>
      <div class="tab new" data-dashboard-target="newTab">
        <span data-action="click->dashboard#new_costume_handler">Create a Sonic<i class="fas fa-plus ms-1" data-dashboard-target="newCostumeIcon"></i></span>
        <%= render 'new-costume', costume: @costume %>
      </div>
    </div>
    <div class="dashboard-wrapper container" data-dashboard-target="dashboard-wrapper">
        <%= render 'homepage' %>
        <%= render 'search-costume' %>
        <%= render 'offers' %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="landing-wrap">
  <div class="container">
    <div class="landing-content">
      <div class="landing-titles">
        <h1>BECOME THE SONIC OF YOUR DREAMS</h1>
        <h5>Explore and enhance your Sonic experience</h5>
      </div>
      <div class="row">
        <div class="fit-searchbar">
          <%= render 'shared/searchbar' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/test.html.erb
<%= render 'pages/searchbar-button' %>

app/views/shared/_card-test.html.erb
<div role="list-item" class="">
  <a href="" class="pack-card-home w-inline-block">
    <div class="card-image-container">
    <img src="" alt="" class="grid-image">
    </div>

    <div class="_40px-divider"></div>

    <div class="paid-label-container">
      <div class="free-label-text">20€</div>
    </div>
    <div class="h2-card-title">TITLE</div>

    <div class="_40px-divider"></div>

    <div class="p-meta">
      "Descirption lorem lorem lorem Descirption lorem lorem lorem Descirption"
    </div>

    <div class="_40px-divider"></div>
  </a>
</div>